name: Deploy playwright report
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allows to run this workflow manually from the Actions tab 
  workflow_dispatch:
  schedule: 
    - cron: '0 19 * * 1'
# Sets permissions of the GITHUB_TOKEN to allow deplooyment to GitHub pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  install:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: cache-playwright
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install Playwright Browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
  test:
    name: 🧪 Test (${{ matrix.shardIndex }}/${{ matrix.shardTotal }})
    needs: install
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
        project: [ExecuteInChrome]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      - name: Run Playwright tests
        run: npx playwright test --project=${{ matrix.project }} --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: monocart-report-${{ matrix.project }}-${{ matrix.shardIndex }}_${{ matrix.shardTotal }}
          path: playwright-monocart-report/
          if-no-files-found: ignore
          retention-days: 1
  report:
    name: Merge and Publish Reports
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [test]
    timeout-minutes: 30
    permissions:
      actions: write
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      - name: Download Artifacts
        id: download-artifacts
        uses: actions/download-artifact@v4
        with:
            path: playwright-monocart-report/data
            pattern: test-results-*
            merge-multiple: true
      - name: Merge Playwright Monocart Reports
        id: merge-playwright-monocart-reports
        run: |
          curl -o result.json https://milicadg.github.io/playwrightBooking/playwright-monocart-report/index.json
          npm run merge:report:monocart
          # chmod +x ./merge-test-reports.sh
          # ./merge-test-reports.sh
      - name: Move to Reports folder
        id: move-to-reports-folder
        run: |
          mv playwright-monocart-report test-results/
        shell: bash
      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        id: upload-pages-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: test-results/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Delete Unnecessary Artifacts
        id: delete-unnecessary-artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            # test-results-*
            monocart-report-*
          failOnError: false